// ig-data.jsx — Dados iniciais para todos os templates (PT-BR, lorem ipsum placeholder)

const IG_DEFAULTS = {
  manifesto01: { quote: 'Lorem ipsum dolor sit amet.\nConsectetur adipiscing.', author: 'L O R E M   I P S U M' },
  manifesto02: { quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore.', author: 'S O B R E   A   M A R C A' },
  manifesto03: { term: 'Lorem', definition: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
  manifesto04: {
    items: [
      { title: 'Lorem',    desc: 'Ipsum dolor sit amet. Consectetur adipiscing elit.' },
      { title: 'Dolor',    desc: 'Sit amet consectetur. Adipiscing elit sed do.' },
      { title: 'Ipsum',    desc: 'Eiusmod tempor incididunt. Ut labore et dolore.' },
      { title: 'Amet',     desc: 'Consectetur adipiscing. Sed do eiusmod tempor.' },
    ],
  },
  manifesto05: {
    intro: 'Lorem ipsum dolor sit amet.',
    statement: 'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
  },
  manifesto06: { word: 'Essencialismo', subtitle: 'lorem ipsum dolor sit amet ·  consectetur adipiscing elit' },
  manifesto07: {
    eyebrow: 'E N S A I O   ·   F U N D A Ç Ã O',
    dropCap: 'L',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    attribution: 'L O R E M   I P S U M   ·   2 0 2 6',
  },

  announce01: {
    kicker: 'N O V O  ·  2 0 2 6',
    name: 'Produto',
    specs: [
      { label: 'V E R S Ã O',           value: 'v1.0' },
      { label: 'P L A T A F O R M A',   value: 'Linux · macOS' },
      { label: 'L I C E N Ç A',         value: 'AGPL‑3.0' },
      { label: 'D I S P O N Í V E L',   value: 'Q2 · 2026' },
    ],
    date: 'D I S P O N Í V E L   E M   A B R I L',
  },
  announce02: {
    category: 'H A R D W A R E',
    kicker: 'L A N Ç A M E N T O',
    name: 'Lorem One',
    tagline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod.',
    date: 'Q 2  ·  2 0 2 6',
  },
  announce03: {
    name: 'Lorem Módulo',
    subtitle: 'Lorem ipsum dolor sit amet — consectetur, adipiscing et dolor.',
    rows: [
      { label: 'M A T E R I A L',    value: 'Alumínio anodizado' },
      { label: 'C O N E X Ã O',      value: 'USB‑C · NFC' },
      { label: 'C H I P',            value: 'Secure Element EAL6+' },
      { label: 'F I R M W A R E',    value: 'Código aberto · verificável' },
      { label: 'P E S O',            value: '18 g' },
      { label: 'D I M E N S Õ E S',  value: '54 × 19 × 3 mm' },
    ],
    date: '2 0 2 6',
  },
  announce04: {
    headline: 'Lorem ipsum dolor sit amet, consectetur versão 1.0.',
    cta: 'B A I X A R',
    url: 'l o r e m . o r g / p r o d u t o',
    date: '2 0 2 6',
  },
  announce05: {
    kicker: 'L A N Ç A M E N T O',
    name: 'Lorem',
    tagline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod.',
    date: 'A B R . 2 6',
  },
  announce06: {
    name: 'P R O D U T O',
    version: '1.0',
    notes: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt.',
    date: 'A B R I L   ·   2 0 2 6',
  },
  announce07: {
    recipient: 'Lorem ipsum\nconsectetur',
    sender: 'Lorem Ipsum\nDolor Sit Amet',
    product: 'Produto',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing — alumínio anodizado, Secure Element EAL6+ e firmware verificável.',
    shipDate: '2 0 . 0 6 . 2 0 2 6',
    stamp: 'O P E N\nS O U R C E',
    tracking: 'LR-026-PROD-001',
  },

  educational01: {
    question: 'Lorem ipsum dolor sit amet, consectetur adipiscing?',
    steps: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    ],
  },
  educational02: {
    category: 'C R I P T O G R A F I A',
    term: 'Lorem‑ipsum',
    pronunciation: '/ˈloʊrəm ˈɪpsəm/',
    definition: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim.',
  },
  educational03: {
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing?',
    leftLabel: 'M O D E L O   C O M U M',
    leftTitle: 'Lorem ipsum',
    leftText: 'Dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.',
    rightLabel: 'N O S S O   M O D E L O',
    rightTitle: 'Ipsum dolor',
    rightText: 'Lorem sit amet, consectetur adipiscing. Sed do eiusmod tempor ut labore et dolore magna.',
  },
  educational04: {
    number: 'D I C A  ·  0 1',
    tip: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    detail: 'Sed do eiusmod tempor incididunt ut labore. Et dolore magna aliqua, ut enim ad minim veniam.',
    category: 'S E G U R A N Ç A',
    ref: 'T I P   ·  0 0 1',
  },
  educational05: {
    title: 'Lorem ipsum dolor sit amet',
    nodes: [
      'Lorem ipsum gera a transação',
      'Dolor sit amet assina localmente',
      'Consectetur adipiscing enviada à rede — lorem ipsum nunca sai',
      'Sed do eiusmod verifica e propaga',
    ],
  },
  educational06: {
    kicker: 'S O B R E   P R I V A C I D A D E',
    stat: '87 %',
    context: 'lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt.',
    source: 'F O N T E  ·  L O R E M ·  2 0 2 5',
    year: '2 0 2 6',
  },
  educational07: {
    title: 'Três conceitos comuns sobre lorem ipsum.',
    myth1: 'Lorem ipsum é só para esconder coisas ilegais.',
    fact1: 'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
    myth2: 'Sed do eiusmod, não preciso me preocupar.',
    fact2: 'Lorem ipsum dolor sit amet — consectetur adipiscing é poder de escolha, não segredo.',
    myth3: 'Dolor sit amet de código aberto é menos seguro.',
    fact3: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.',
    tag: 'E · 0 7   ·   2 0 2 6',
  },

  carouselCover: {
    kicker: 'C A R R O S S E L   ·   4   S L I D E S',
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing.',
    subtitle: 'Lorem ipsum dolor sit amet — consectetur adipiscing, sed do eiusmod, tempor, incididunt.',
    total: 5,
  },
  carouselPage1: {
    num: '0 1', label: 'L O R E M',
    eyebrow: 'P R I N C Í P I O  ·  0 1',
    heading: 'Lorem ipsum.',
    body: 'Dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore.',
    counter: '2 / 5',
  },
  carouselPage2: {
    num: '0 2', label: 'I P S U M',
    eyebrow: 'P R I N C Í P I O  ·  0 2',
    heading: 'Dolor sit amet.',
    body: 'Consectetur adipiscing elit, sed do eiusmod tempor. Incididunt ut labore et dolore magna aliqua.',
    counter: '3 / 5',
  },
  carouselPage3: {
    num: '0 3', label: 'D O L O R',
    eyebrow: 'P R I N C Í P I O  ·  0 3',
    heading: 'Consectetur adipiscing.',
    body: 'Sed do eiusmod tempor incididunt ut labore. Ut enim ad minim veniam quis nostrud exercitation.',
    counter: '4 / 5',
  },
  carouselCTA: {
    headline: 'Lorem ipsum dolor sit amet consectetur.',
    cta: 'A C E S S A R',
    note: 'Lorem ipsum dolor sit amet, consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore.',
    url: 'l o r e m . o r g / i p s u m',
    counter: '5 / 5',
  },

  event01: { kicker: 'E N C O N T R O   A B E R T O', day: '12', monthYear: 'J U N H O   ·   2 0 2 6', title: 'Lorem ipsum dolor sit amet: consectetur adipiscing.', place: 'S Ã O   P A U L O  ·  S P' },
  event02: { title: 'Lorem Ipsum 2026', date: '1 2 . 0 6 . 2 6', time: '1 9 h 0 0', place: 'T E A T R O   O F I C I N A', url: 'l o r e m . o r g / e v e n t o' },
  event03: { title: 'Lorem ipsum dolor', date: '1 2  ·  J U N  ·  2 6', place: 'S P', schedule: [
    { time: '19:00', item: 'Abertura — Lorem ipsum' },
    { time: '19:30', item: 'Painel — Dolor sit amet na prática' },
    { time: '20:45', item: 'Demonstrações técnicas (Produto A, Produto B)' },
    { time: '21:30', item: 'Encerramento e perguntas' },
  ]},
  event04: { kicker: 'R S V P   A B E R T O', title: 'Lorem Ipsum · 2026', when: '12 de junho · 19h', where: 'Teatro Oficina  ·  SP', url: 'L O R E M . O R G / E V E N T O' },
  event05: { dateLine: '1 2 . 0 6 . 2 0 2 6', title: 'Lorem ipsum dolor sit amet consectetur adipiscing.', body: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', place: 'S Ã O   P A U L O', url: 'L O R E M . O R G / E V E N T O' },
  event06: { title: 'Lorem Ipsum  ·  Edição 2026', date: '12  ·  Junho  ·  2026', place: 'S Ã O   P A U L O  ·  S P' },
  event07: {
    title: 'Lorem Ipsum · 2026',
    date: '12 . 06 . 2026',
    gate: '0 3 A',
    city: 'S Ã O   P A U L O',
    passNum: '0 0 1',
    url: 'L O R E M . O R G / E V E N T O',
  },

  job01: { department: 'E N G E N H A R I A', role: 'Engenheiro(a) de Lorem', type: 'T e m p o   i n t e g r a l', location: 'R e m o t o   ·   L A T A M', level: 'S ê n i o r', url: 'L O R E M . O R G / V A G A S' },
  job02: { kicker: 'J U N T E - S E   A O   N Ú C L E O', role: 'Designer de Lorem', summary: 'Lorem ipsum dolor sit amet consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim.', cta: 'C A N D I D A T A R', deadline: 'A T É   3 0 . 0 4' },
  job03: { role: 'Engenheiro(a) de Lorem', department: 'H A R D W A R E  ·  P R O D U T O', requirements: [
    'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    'Sed do eiusmod tempor incididunt ut labore et dolor.',
    'Ut enim ad minim veniam quis nostrud exercitation — lorem ipsum.',
    'Consectetur adipiscing prévio a projetos (valorizado).',
  ], url: 'L O R E M . O R G / V A G A S' },
  job04: { kicker: 'C A R R E I R A S   L O R E M', role: 'Pesquisador(a) em lorem ipsum', location: 'R E M O T O   ·   G L O B A L' },
  job05: { intro: 'Procura‑se', role: 'Engenheiro(a) de Lorem Ipsum', model: 'H í b r i d o   ·   S P', start: 'M a i o   ·   2 0 2 6', url: 'L O R E M . O R G / V A G A S' },
  job06: { tagline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore.', url: 'L O R E M . O R G / V A G A S', roles: [
    { title: 'Engenheiro(a) de Lorem', team: 'E N G E N H A R I A' },
    { title: 'Designer de Ipsum',      team: 'D E S I G N' },
    { title: 'Pesquisador(a) de Dolor', team: 'P & D' },
    { title: 'Escritor(a) de Amet',    team: 'D O C S' },
  ] },
  job07: {
    headline: 'Lorem ipsum dolor sit amet.',
    sym1: '⊕', title1: 'Lorem ipsum',     desc1: 'Dolor sit amet consectetur. Adipiscing elit sed do eiusmod tempor.',
    sym2: '◇', title2: 'Ipsum dolor',     desc2: 'Consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore.',
    sym3: '⏣', title3: 'Dolor amet',      desc3: 'Ut enim ad minim veniam. Quis nostrud exercitation ullamco laboris.',
    sym4: '◐', title4: 'Amet lorem',      desc4: 'Consectetur adipiscing. Sed do eiusmod tempor incididunt labore.',
    url: 'L O R E M . O R G / V A G A S',
  },

  blog01: { category: 'E S C R I T O S  ·  T É C N I C O', title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', excerpt: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.', readTime: '7   M I N', url: 'L O R E M . O R G / B L O G' },
  blog02: { tags: ['C R I P T O G R A F I A', 'E N S A I O'], title: 'Lorem ipsum dolor sit amet: consectetur adipiscing elit.', author: 'E Q U I P E   L O R E M', date: '2 3 . 0 4 . 2 6', url: 'L O R E M . O R G / B L O G' },
  blog03: { kicker: 'N o v o   n o   b l o g', title: 'Lorem ipsum dolor, non sit amet.', subtitle: 'Consectetur adipiscing elit — sed do eiusmod tempor incididunt ut labore et dolore.', readTime: '1 1   M I N', author: 'E Q U I P E   L O R E M' },
  blog04: { number: '04', series: 'S É R I E  ·  F U N D A M E N T O S', title: 'Lorem ipsum dolor sit amet em 2026?', excerpt: 'Quarto artigo da série sobre lorem ipsum — consectetur adipiscing ut labore et dolore magna aliqua.', url: 'L O R E M . O R G / B L O G' },
  blog05: { title: 'Lorem ipsum dolor sit amet: notas sobre consectetur.', author: 'E q u i p e   L o r e m', readTime: '9   m i n', url: 'L O R E M . O R G / B L O G', date: '2 3 . 0 4 . 2 6' },
  blog06: { headline: 'Novidades desta semana no blog.', articles: [
    { title: 'Lorem ipsum: consectetur adipiscing elit',   time: '1 1   m i n' },
    { title: 'Dolor sit amet na prática: três exemplos',   time: '8   m i n' },
    { title: 'Por que lorem ipsum por padrão',             time: '6   m i n' },
    { title: 'Consectetur adipiscing: notas de design',    time: '9   m i n' },
  ], url: 'L O R E M . O R G / B L O G' },
  blog07: {
    section: 'E D I T O R I A L  ·  T É C N I C O',
    date: '2 5 . 0 4 . 2 6',
    title: 'Lorem ipsum dolor sit amet.',
    dek: 'Consectetur adipiscing elit — sed do eiusmod tempor incididunt.',
    byline: 'P O R   E Q U I P E   L O R E M',
    readTime: '1 2   M I N',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti.',
    url: 'L O R E M . O R G / B L O G',
  },

  transp01: {
    title: 'Lorem ipsum dolor sit amet.',
    label1: 'Lorem ipsum auditado',        val1: '92',
    label2: 'Repositórios públicos',        val2: '100',
    label3: 'Issues documentadas',          val3: '87',
    label4: 'Dependências lorem ipsum',     val4: '74',
    tag: '2 0 2 6',
  },
  transp02: {
    heroLabel: 'P R I N C Í P I O',
    hero: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    cell1l: 'C Ó D I G O',      cell1v: '100% aberto',
    cell2l: 'A U D I T O R I A', cell2v: 'Externa · anual',
    cell3l: 'S E R V I D O R',   cell3v: 'Zero custódia',
    cell4l: 'L I C E N Ç A',    cell4v: 'AGPL-3.0',
  },
  transp03: {
    title: 'Lorem ipsum dolor.',
    year1: '2 0 2 4', event1: 'Lorem ipsum. Primeiros experimentos com dolor sit amet.',
    year2: '2 0 2 5', event2: 'Consectetur em beta. Adipiscing em prototipagem. Auditoria contratada.',
    year3: '2 0 2 6', event3: 'Lorem 1.0 lançado. Auditoria pública concluída. Ipsum em campo.',
  },
  transp04: {
    band: '1 0 0 %   C Ó D I G O   A B E R T O',
    above: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.',
    below: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.',
    source: 'L I C E N Ç A   ·   A G P L - 3 . 0   ·   L O R E M',
  },
  transp05: {
    statement: 'Lorem ipsum dolor sit amet consectetur adipiscing.',
    note1: 'Lorem ipsum dolor sit amet: consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.',
    note2: 'Dolor sit amet consectetur — sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    note3: 'Lorem ipsum adipiscing conduzida anualmente. Relatório publicado em lorem.org/auditoria.',
  },
  transp06: {
    title: 'O que não fazemos.',
    label1: 'Coleta de telemetria',   value1: 'Nunca',
    label2: 'Custódia de chaves',     value2: 'Nunca',
    label3: 'Login centralizado',     value3: 'Nunca',
    label4: 'Venda de dados',         value4: 'Nunca',
    label5: 'Software proprietário',  value5: 'Nunca',
  },
  transp07: {
    title: 'Lorem ipsum dolor sit amet consectetur.',
    label1: 'Lorem ipsum · core',     val1: '52 %',
    label2: 'Auditoria e segurança',  val2: '28 %',
    label3: 'Documentação e ensino',  val3: '20 %',
    totalLabel: '100',
    tag: '2 0 2 6',
  },

  product01: {
    kicker: 'S O F T W A R E',
    name: 'Produto',
    spec1l: 'P L A T A F O R M A',        spec1v: 'Linux · macOS · Windows',
    spec2l: 'L I C E N Ç A',              spec2v: 'AGPL-3.0',
    spec3l: 'C R I P T O G R A F I A',    spec3v: 'Ed25519 · AES-256-GCM',
    spec4l: 'B A C K U P',                spec4v: 'BIP-39 seed phrase',
    spec5l: 'A U T E N T I C A Ç Ã O',    spec5v: 'Local · sem servidor',
    spec6l: 'D I S P O N I B I L I D A D E', spec6v: 'Gratuito · código aberto',
  },
  product02: {
    product: 'Produto',
    stat: '256',
    unit: 'bit AES',
    context: 'Lorem ipsum dolor sit amet, AES-256-GCM. Consectetur adipiscing elit.',
    tag: 'S E G U R A N Ç A',
  },
  product03: {
    title: 'Lorem Ipsum · 2026',
    date1: 'Q 1   ·   2 0 2 6',  product1: 'Lorem v1.0',   note1: 'Lorem ipsum dolor sit amet. AGPL-3.0.',
    date2: 'Q 2   ·   2 0 2 6',  product2: 'Ipsum',         note2: 'Lorem ipsum dolor sit consectetur amet.',
    date3: 'Q 4   ·   2 0 2 6',  product3: 'Lorem v2.0',    note3: 'Dolor amet consectetur + Hardware Security Module.',
  },
  product04: {
    name: 'Módulo',
    version: 'H A R D W A R E   ·   V 1 . 0   ·   2 0 2 6',
    description: 'Lorem ipsum dolor sit amet consectetur. Alumínio anodizado, chip EAL6+, firmware auditável.',
    specs: 'USB-C  ·  NFC  ·  18 g  ·  EAL6+\nAGPL-3.0  ·  54 × 19 × 3 mm',
    tag: 'L O R E M   H A R D W A R E',
  },
  product05: {
    product: 'Produto',
    rel1: 'v 1.0  ·  Abril 2026',  notes1: 'Lorem ipsum dolor sit amet. Consectetur adipiscing. Auditoria externa concluída. Licença AGPL-3.0.',
    rel2: 'v 1.1  ·  Junho 2026',  notes2: 'Dolor sit amet BIP-39. Consectetur adipiscing offline. Lorem ipsum com módulo.',
    rel3: 'v 2.0  ·  Q4 2026',     notes3: 'Lorem Tauri desktop. Hardware Security Module. Sincronização multi-device.',
  },
  product06: {
    kicker: 'F I C H A   T É C N I C A',
    name: 'Lorem Módulo',
    r1l: 'M A T E R I A L',   r1v: 'Alumínio anodizado',
    r2l: 'C O N E X Ã O',     r2v: 'USB-C · NFC',
    r3l: 'C H I P',           r3v: 'Secure Element EAL6+',
    r4l: 'F I R M W A R E',   r4v: 'Código aberto · verificável',
    r5l: 'P E S O',           r5v: '18 g',
    r6l: 'D I M E N S Õ E S', r6v: '54 × 19 × 3 mm',
  },
  product07: {
    title: 'Lorem vs. soluções convencionais.',
    colA: 'Lorem',
    colB: 'Outros',
    attr1: 'Código aberto e auditável',                a1: '✓', b1: '—',
    attr2: 'Chaves geradas e mantidas localmente',     a2: '✓', b2: '×',
    attr3: 'Sem servidor de autenticação',             a3: '✓', b3: '×',
    attr4: 'Backup via BIP-39 offline',                a4: '✓', b4: '—',
    attr5: 'Custódia de terceiros',                    a5: '×', b5: '✓',
    tag: 'P · 0 7   ·   2 0 2 6',
  },

  testimonial01: {
    initial: 'L',
    quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore.',
    author: 'Lorem Ipsum',
    role: 'Lorem Dolor · Ipsum SP',
  },
  testimonial02: {
    highlight: '"Lorem ipsum dolor sit amet consectetur."',
    quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.',
    author: 'Lorem Ipsum',
    role: 'Lorem Dolor · Ipsum SP',
  },
  testimonial03: {
    author: 'Ipsum Lorem',
    role: 'Lorem ipsum consectetur',
    company: 'A G Ê N C I A   L O R E M   ·   S P',
    quote: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  testimonial04: {
    date: '1 5 . 0 4 . 2 0 2 6',
    salutation: 'Para lorem ipsum,',
    quote: 'Lorem ipsum dolor sit amet consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim veniam.',
    author: 'Dolor Lorem',
    role: 'Lorem Ipsum · Dolor',
  },
  testimonial05: {
    product: 'Produto',
    feature: 'G E R E N C I A M E N T O   D E   L O R E M',
    quote: 'Lorem ipsum dolor sit amet consectetur. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    author: 'Ipsum Lorem Dolor',
    role: 'Lorem Developer · Ipsum Contributor',
  },
  testimonial06: {
    company: 'Lorem',
    author: 'Dolor Ipsum Lorem',
    role: 'Lorem · Ipsum Dolor',
    quote: 'Lorem ipsum dolor sit amet consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  testimonial07: {
    initial: 'L',
    author: 'Lorem Ipsum',
    role: 'Pesquisadora · Lorem ipsum',
    quote: 'Lorem ipsum dolor sit amet consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore et dolore magna.',
    memberId: 'LR-2024-0837',
    since: '0 8 . 2 0 2 4',
  },

  usecase01: {
    sector: 'L O R E M   I P S U M',
    persona: 'Lorem ipsum dolor',
    scenario: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    tool: 'Produto',
    result: 'Lorem ipsum dolor sit amet',
    tag: '2 0 2 6',
  },
  usecase02: {
    eyebrow: 'Lorem ipsum dolor sit amet consectetur adipiscing.',
    challengeText: 'Lorem ipsum dolor sit amet. Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.',
    solutionText: 'Dolor sit amet consectetur lorem ipsum. Sed do eiusmod tempor incididunt; operação contínua sem ele.',
    resultText: 'Lorem ipsum dolor sit amet consectetur. Sed do eiusmod tempor incididunt. Zero dependência.',
  },
  usecase03: {
    sector: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore et dolore.',
    tool: 'P R O D U T O   ·   L O R E M   I P S U M',
    context: 'L O R E M   I P S U M   ·   D O L O R',
  },
  usecase04: {
    persona: 'Lorem ipsum',
    before: 'Lorem ipsum dolor sit amet consectetur. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    now: 'Lorem ipsum dolor amet. Consectetur adipiscing elit. Sed do eiusmod tempor — nenhum dado exposto.',
    tool: 'P R O D U T O   ·   L O R E M',
  },
  usecase05: {
    title: 'Lorem ipsum dolor sit amet.',
    who: 'Lorem Ipsum · Dolor · SP',
    what: 'Lorem ipsum dolor sit amet consectetur adipiscing elit',
    how: 'Sed do eiusmod · tempor incididunt · lorem ipsum',
    outcome: 'Lorem ipsum 40% · consectetur antes · dolor ipsum',
  },
  usecase06: {
    title: 'Lorem ipsum dolor sit amet.',
    sector1: 'L O R E M',
    case1: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    tool1: 'P R O D U T O',
    sector2: 'I P S U M',
    case2: 'Dolor sit amet consectetur adipiscing — lorem ipsum por qualquer parte.',
    tool2: 'P R O D U T O   +   P L A T A F O R M A',
    sector3: 'D O L O R',
    case3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    tool3: 'P R O D U T O',
  },
  usecase07: {
    title: 'Lorem Ipsum · primeiro semestre de operação.',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    label1: 'U N I D A D E S',                  val1: '8',    unit1: 'unidades',
    label2: 'D I S P O S I T I V O S',          val2: '32',   unit2: 'devices',
    label3: 'R E D U Ç Ã O   D E   P E R D A',  val3: '−40',  unit3: '%',
    label4: 'D A D O S   E M   C U S T Ó D I A', val4: '0',   unit4: 'servidores',
    context: 'D A D O S   ·   2 0 2 6',
    year: 'Q 2  ·  2 6',
  },

  tutorial01: {
    category: 'C O M O   F A Z E R',
    title: 'Lorem ipsum dolor sit amet em 4 passos.',
    step1: 'Lorem ipsum dolor em lorem.org/produto',
    step2: 'Consectetur adipiscing e confirme as permissões',
    step3: 'Gere seu par de chaves ipsum localmente',
    step4: 'Lorem dolor sit amet offline e em local seguro',
    tag: 'P R O D U T O',
  },
  tutorial02: {
    title: 'Lorem ipsum vs. dolor sit amet.',
    before: 'Lorem ipsum dolor sit amet. Consectetur adipiscing condicionado ao login. Sed do eiusmod tempor incididunt.',
    after: 'Dolor sit amet lorem ipsum. Consectetur adipiscing elit nenhum servidor intermedia. Ut enim ad minim veniam.',
  },
  tutorial03: {
    context: 'Lorem CLI',
    line1: 'lorem init --keygen ed25519',
    line2: 'lorem sign --key ~/.lorem/id.key contrato.pdf',
    line3: 'lorem verify --pub ~/.lorem/id.pub contrato.pdf',
    line4: 'lorem export --format bip39',
    line5: '',
    tag: 'C L I   ·   L O R E M',
  },
  tutorial04: {
    category: 'S E G U R A N Ç A   ·   L O R E M',
    label: 'D I C A',
    tip: 'Lorem ipsum dolor sit amet consectetur. Papel ou metal — sem nuvem.',
    context: 'B o a s   p r á t i c a s   ·   L o r e m',
  },
  tutorial05: {
    title: 'Lorem ipsum dolor sit amet.',
    item1: 'Lorem ipsum em todos os repositórios',
    item2: 'Dolor sit amet testada do zero',
    item3: 'Lorem ipsum fora do histórico git',
    item4: 'CI verificando consectetur nas plataformas-alvo',
    item5: 'Política de contribuição (CONTRIBUTING.md)',
    tag: 'S O F T W A R E   L I V R E',
  },
  tutorial06: {
    category: 'F L U X O   ·   L O R E M',
    title: 'Como lorem ipsum dolor sit amet funciona.',
    node1: 'Lorem ipsum dolor sit amet. Nunca sai do dispositivo.',
    node2: 'Dolor ipsum assina localmente. Gera uma assinatura de 64 bytes.',
    node3: 'Consectetur verifica com chave pública — sem revelar a chave privada.',
    tag: 'C R I P T O G R A F I A',
  },
  tutorial07: {
    title: 'Lorem ipsum precisa de hardware dedicado?',
    q1: 'Dolor sit amet consectetur adipiscing — lorem ipsum em ambiente compartilhado.',
    yes: 'Lorem ipsum dolor. Hardware dedicado isola a chave do sistema operacional e exige confirmação física.',
    no: 'Consectetur adipiscing sit amet é suficiente. Lorem dolor ipsum offline em papel ou metal.',
    tag: 'S E G U R A N Ç A',
  },

  quote01: {
    quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.',
    author: 'Lorem Ipsum',
    role: 'Lorem · Ipsum · 1900–1944',
    year: '2 0 2 6',
  },
  quote02: {
    date: '1 9 8 4',
    quote: 'Lorem ipsum dolor sit amet consectetur adipiscing. Sed do eiusmod tempor incididunt ut labore et dolore.',
    author: 'Lorem Ipsum',
    context: 'L O R E M   I P S U M   ·   D O L O R   S I T   A M E T',
  },
  quote03: {
    quote: 'Lorem ipsum.\nNon dolor amet.',
    author: 'Ipsum Lorem',
    year: '1 9 7 6',
  },
  quote04: {
    eyebrow: 'V O Z   E X T E R N A   ·   D E S I G N',
    author: 'Lorem Ipsum',
    source: 'Lorem Dolor Sit Amet  ·  1976',
    quote: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam.',
  },
  quote05: {
    quoteA: 'Lorem ipsum dolor sit amet consectetur adipiscing.',
    authorA: 'Lorem Ipsum',
    roleA: 'Lorem Dolor · Ipsum Amet',
    quoteB: 'Sed do eiusmod tempor incididunt ut labore et dolore.',
    authorB: 'Ipsum Dolor',
    roleB: 'Consectetur Adipiscing · Lorem Ipsum',
  },
  quote06: {
    eyebrow: 'E N S A I O   ·   T E C N O L O G I A',
    quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam.',
    author: 'Lorem Ipsum',
    role: 'Lorem Dolor · Ipsum Amet',
    detail: '2 0 2 3',
  },
  quote07: {
    eyebrow: 'A N O T A Ç Ã O   ·   M A R G I N Á L I A',
    note1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit de 1975, in reprehenderit in voluptate velit.',
    note2: 'Dolor sit amet consectetur retomado três décadas depois nos debates sobre lorem ipsum pós-2000.',
    quote: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
    author: 'Lorem Ipsum',
    source: 'L o r e m   I p s u m   D o l o r   ·   1 9 9 1',
    tag: '2 0 2 6',
  },

  manifesto08: {
    lines: [
      'Lorem',
      'ipsum',
      'dolor sit',
      'amet',
      'consectetur.',
    ],
  },
  announce08: {
    name: 'Módulo',
    tag: '2 0 2 6',
    callouts: [
      { pos: 'tl', label: 'M A T E R I A L',  spec: 'Alumínio anodizado' },
      { pos: 'tr', label: 'C H I P',           spec: 'Secure Element EAL6+' },
      { pos: 'bl', label: 'F I R M W A R E',   spec: 'Código aberto' },
      { pos: 'br', label: 'C O N E X Ã O',     spec: 'USB-C · NFC' },
    ],
  },
  educational08: {
    title: 'Lorem ipsum dolor sit amet.',
    onlyA: 'Lorem\nipsum',
    both: 'Produto',
    onlyB: 'Dolor\nConsectetur',
  },
  event08: {
    month: 'J U N H O   ·   2 0 2 6',
    title: 'Lorem Ipsum',
    location: 'S Ã O   P A U L O  ·  S P',
    day: '12',
    startWeekday: 0,
    daysInMonth: 30,
  },
  job08: {
    headline: 'Lorem ipsum dolor sit amet.',
    url: 'L O R E M . O R G / V A G A S',
    levels: [
      { title: 'Sênior', desc: 'Lorem ipsum · consectetur · responde por adipiscing',   width: 44 },
      { title: 'Pleno',  desc: 'Dolor sit amet · decisões autônomas · lorem ipsum',     width: 68 },
      { title: 'Júnior', desc: 'Lorem ipsum adipiscing · suporte direto · consectetur', width: 92 },
    ],
  },
  blog08: {
    kicker: 'L O R E M  ·  P U B L I C A Ç Ã O   T R I M E S T R A L',
    title: 'Sumário · Edição 02',
    url: 'L O R E M . O R G / B L O G',
    chapters: [
      { title: 'Lorem ipsum dolor sit amet',   page: '0 0 4' },
      { title: 'Consectetur adipiscing elit',  page: '0 1 8' },
      { title: 'Sed do eiusmod tempor',         page: '0 3 6' },
      { title: 'Lorem ipsum · 6 meses',        page: '0 5 4' },
      { title: 'O que vem depois',             page: '0 8 2' },
    ],
  },
  transp08: {
    title: 'Lorem ipsum dolor sit amet — últimas 4 semanas.',
    tag: '2 0 2 6',
    rowLabels: ['S e m   1', 'S e m   2', 'S e m   3', 'S e m   4'],
    matrix: [
      [0.2, 0.4, 0.6, 0.3, 0.7, 0.9, 0.8],
      [0.5, 0.6, 0.8, 0.9, 0.7, 0.4, 0.3],
      [0.7, 0.5, 0.4, 0.6, 0.5, 0.8, 0.6],
      [0.9, 0.8, 0.6, 0.5, 0.7, 0.6, 0.5],
    ],
  },
  product08: {
    product: 'Produto',
    subtitle: 'Lorem ipsum dolor — quatro camadas.',
    layers: [
      { level: 'L4', name: 'Interface',    desc: 'CLI · Desktop Tauri · Web (futuro)' },
      { level: 'L3', name: 'Domínio',      desc: 'Lorem ipsum · dolor · consectetur' },
      { level: 'L2', name: 'Criptografia', desc: 'Ed25519 · AES-256-GCM · Argon2id' },
      { level: 'L1', name: 'Hardware',     desc: 'Secure Element opcional · Módulo (NFC + USB-C)' },
    ],
  },
  testimonial08: {
    quotes: [
      { text: '"Lorem ipsum dolor."',
        author: 'L o r e m   I .   ·   D e v',
        pos: { top: '14%',  left: '6%'  } },
      { text: '"Consectetur adipiscing sit amet."',
        author: 'I p s u m   D .   ·   G O',
        pos: { top: '32%',  right: '5%' } },
      { text: '"Lorem dolor devolve o controle."',
        author: 'D o l o r   L .   ·   S P',
        pos: { top: '58%',  left: '10%' } },
      { text: '"Ipsum lorem — consectetur adipiscing."',
        author: 'A m e t   L .   ·   P E',
        pos: { top: '76%',  right: '8%' } },
    ],
  },
  usecase08: {
    title: 'Lorem ipsum dolor atividade',
    window: 'Últimas 4 horas · 25 abr 2026',
    events: [
      { time: '0 4 : 1 2', loc: 'Curitiba · PR',
        action: 'Lorem ipsum T-03 reportou dolor 6.4 — alerta normal.' },
      { time: '0 3 : 4 7', loc: 'Goiânia · GO',
        action: 'Nova lorem ipsum consectetur adipiscing.' },
      { time: '0 2 : 5 1', loc: 'Joinville · SC',
        action: 'Bloco assinado por chave Ed25519 do lorem.' },
      { time: '0 2 : 0 4', loc: 'Recife · PE',
        action: 'Lorem ipsum de 12 sensores sincronizada via dolor sit amet.' },
      { time: '0 1 : 3 8', loc: 'São Paulo · SP',
        action: 'Onboarding de novo nó no lorem ipsum.' },
    ],
  },
  tutorial08: {
    title: 'Lorem ipsum dolor sit amet.',
    tree: [
      { prefix: '',         name: '~/.lorem/',    annot: 'diretório raiz' },
      { prefix: '├──',      name: 'id.key',       annot: 'chave privada · 0600' },
      { prefix: '├──',      name: 'id.pub',       annot: 'chave pública · 0644' },
      { prefix: '├──',      name: 'config.toml',  annot: 'preferências locais' },
      { prefix: '└──',      name: 'backup/',      annot: 'cópia offline' },
      { prefix: '    ├──',  name: 'seed.bip39',   annot: 'frase-semente · ler offline' },
      { prefix: '    └──',  name: 'module.fw',    annot: 'firmware do módulo' },
    ],
  },
  quote08: {
    quote: 'Lorem ipsum\ndolor sit,\namet.',
    author: 'L O R E M   I P S U M',
    curved: '· L O R E M · 2 0 2 6 · I P S U M · D O L O R · L O R E M · 2 0 2 6 ·',
  },
};

export { IG_DEFAULTS };
