// ig-data.jsx — Dados iniciais para todos os templates (PT-BR, coerente com o manual)

const IG_DEFAULTS = {
  manifesto01: { quote: 'Cada traço é intencional.\nNada em excesso.', author: 'A R A T E K I' },
  manifesto02: { quote: 'A privacidade não é um recurso. É uma condição do software livre.', author: 'S O B R E   A   M A R C A' },
  manifesto03: { term: 'Soberania', definition: 'Autonomia técnica sobre os dados, as chaves e o próprio código que os processa.' },
  manifesto04: {
    items: [
      { title: 'Minimalismo', desc: 'Nada em excesso. Cada elemento intencional.' },
      { title: 'Precisão',    desc: 'Geometria rigorosa, proporções calculadas.' },
      { title: 'Atemporalidade', desc: 'Resistente a tendências, visualmente longeva.' },
      { title: 'Sobriedade',  desc: 'Confiança pela restrição.' },
    ],
  },
  manifesto05: {
    intro: 'Software e hardware livres.',
    statement: 'Segurança, privacidade, tecnologias descentralizadas, autonomia do usuário.',
  },
  manifesto06: { word: 'Essencialismo', subtitle: 'cada elemento cumpre um papel preciso ·  nada é decorativo' },
  manifesto07: {
    eyebrow: 'E N S A I O   ·   F U N D A Ç Ã O',
    dropCap: 'A',
    body: 'Arateki nasce de uma convicção: ferramentas devem servir a quem as usa, não vigiá-lo. Essa diferença, que parece sutil, é o que separa software livre de software conveniente. Construímos sistemas em que dados, chaves e identidade pertencem ao usuário — não ao servidor, não à plataforma, não a um modelo de negócio. Cada decisão técnica responde à mesma pergunta: este código fortalece a autonomia de quem o executa? Se a resposta é não, ele não entra no produto. A simplicidade que vemos na superfície não é estilo: é consequência. Quando o objetivo é claro, o supérfluo cai sozinho.',
    attribution: 'A R A T E K I   ·   2 0 2 6',
  },

  announce01: {
    kicker: 'N O V O  ·  2 0 2 6',
    name: 'Vault',
    specs: [
      { label: 'V E R S Ã O', value: 'v1.0' },
      { label: 'P L A T A F O R M A', value: 'Linux · macOS' },
      { label: 'L I C E N Ç A', value: 'AGPL‑3.0' },
      { label: 'D I S P O N Í V E L', value: 'Q2 · 2026' },
    ],
    date: 'D I S P O N Í V E L   E M   A B R I L',
  },
  announce02: {
    category: 'H A R D W A R E',
    kicker: 'L A N Ç A M E N T O',
    name: 'Arateki One',
    tagline: 'Um dispositivo de identidade soberana, construído sobre hardware aberto.',
    date: 'Q 2  ·  2 0 2 6',
  },
  announce03: {
    name: 'Arateki Shield',
    subtitle: 'Módulo de chaves offline — aço, silício e código.',
    rows: [
      { label: 'M A T E R I A L',  value: 'Alumínio anodizado' },
      { label: 'C O N E X Ã O',    value: 'USB‑C · NFC' },
      { label: 'C H I P',          value: 'Secure Element EAL6+' },
      { label: 'F I R M W A R E',  value: 'Código aberto · verificável' },
      { label: 'P E S O',          value: '18 g' },
      { label: 'D I M E N S Õ E S', value: '54 × 19 × 3 mm' },
    ],
    date: '2 0 2 6',
  },
  announce04: {
    headline: 'A versão 1.0 do Vault já está disponível.',
    cta: 'B A I X A R',
    url: 'a r a t e k i . o r g / v a u l t',
    date: '2 0 2 6',
  },
  announce05: {
    kicker: 'L A N Ç A M E N T O',
    name: 'Bastion',
    tagline: 'Identidade descentralizada para quem opera em rede hostil.',
    date: 'A B R . 2 6',
  },
  announce06: {
    name: 'V A U L T',
    version: '1.0',
    notes: 'Nova arquitetura de chaves. Auditoria externa concluída. Interface reduzida ao essencial.',
    date: 'A B R I L   ·   2 0 2 6',
  },
  announce07: {
    recipient: 'Comunidade\nde código aberto',
    sender: 'Arateki\nLaboratório de Sistemas',
    product: 'Shield',
    description: 'Módulo físico de identidade soberana — alumínio anodizado, Secure Element EAL6+ e firmware verificável.',
    shipDate: '2 0 . 0 6 . 2 0 2 6',
    stamp: 'O P E N\nS O U R C E',
    tracking: 'AR-026-SHLD-001',
  },

  educational01: {
    question: 'Como o Vault protege suas chaves privadas?',
    steps: [
      'As chaves são geradas localmente, nunca tocam a rede.',
      'Toda operação sensível exige confirmação no dispositivo físico.',
      'O código é aberto, verificável e auditado externamente.',
    ],
  },
  educational02: {
    category: 'C R I P T O G R A F I A',
    term: 'Zero‑knowledge',
    pronunciation: '/ˈzɪəroʊ ˈnɒlɪdʒ/',
    definition: 'Protocolo em que uma parte prova à outra que conhece um valor, sem revelar qualquer informação sobre ele além da própria validade da afirmação.',
  },
  educational03: {
    title: 'Por que não usamos contas na nuvem?',
    leftLabel: 'M O D E L O   C O M U M',
    leftTitle: 'Dados no servidor',
    leftText: 'Login centralizado, chaves em custódia de terceiros, vetor de ataque único.',
    rightLabel: 'A R A T E K I',
    rightTitle: 'Dados no usuário',
    rightText: 'Identidade local, chaves no dispositivo, sem intermediário entre você e seus dados.',
  },
  educational04: {
    number: 'D I C A  ·  0 1',
    tip: 'Nunca armazene sua frase‑semente em um serviço online.',
    detail: 'Papel, metal ou um módulo físico dedicado. O mínimo: fora da rede, fora da nuvem, fora do celular.',
    category: 'S E G U R A N Ç A',
    ref: 'T I P   ·  0 0 1',
  },
  educational05: {
    title: 'Fluxo de assinatura descentralizada',
    nodes: [
      'Cliente gera a transação',
      'Vault assina localmente com chave privada',
      'Assinatura enviada à rede — chave nunca sai do dispositivo',
      'Nó verifica e propaga',
    ],
  },
  educational06: {
    kicker: 'S O B R E   P R I V A C I D A D E',
    stat: '87 %',
    context: 'dos aplicativos rastreiam dados do usuário sem necessidade técnica para seu funcionamento.',
    source: 'F O N T E  ·  E F F ·  2 0 2 5',
    year: '2 0 2 6',
  },
  educational07: {
    title: 'Três mal-entendidos comuns sobre criptografia.',
    myth1: 'Criptografia é só para esconder coisas ilegais.',
    fact1: 'É a base de todo HTTPS, banco online, mensagem privada e voto eletrônico.',
    myth2: 'Se não tenho nada a esconder, não preciso me preocupar.',
    fact2: 'Privacidade é poder de escolha sobre o que é compartilhado — não é segredo.',
    myth3: 'Software de código aberto é menos seguro.',
    fact3: 'Quanto mais olhos auditam o código, menos espaço para falhas e backdoors.',
    tag: 'E · 0 7   ·   2 0 2 6',
  },

  carouselCover: {
    kicker: 'C A R R O S S E L   ·   4   S L I D E S',
    title: 'Quatro princípios que guiam o Arateki.',
    subtitle: 'Um guia curto sobre o que nos move — minimalismo, precisão, atemporalidade, sobriedade.',
    total: 5,
  },
  carouselPage1: {
    num: '0 1', label: 'M I N I M A L I S M O',
    eyebrow: 'P R I N C Í P I O  ·  0 1',
    heading: 'Nada em excesso.',
    body: 'Cada elemento cumpre um papel preciso e nada é adicionado por ornamento. A restrição é o método.',
    counter: '2 / 5',
  },
  carouselPage2: {
    num: '0 2', label: 'P R E C I S Ã O',
    eyebrow: 'P R I N C Í P I O  ·  0 2',
    heading: 'Geometria rigorosa.',
    body: 'Proporções calculadas, ângulos intencionais. A marca se sustenta porque cada traço foi pensado.',
    counter: '3 / 5',
  },
  carouselPage3: {
    num: '0 3', label: 'A T E M P O R A L I D A D E',
    eyebrow: 'P R I N C Í P I O  ·  0 3',
    heading: 'Além das tendências.',
    body: 'A identidade é construída para durar. Não depende de modas; depende de consistência.',
    counter: '4 / 5',
  },
  carouselCTA: {
    headline: 'Leia o manifesto completo.',
    cta: 'A C E S S A R',
    note: 'O documento integral está disponível em PDF no site oficial. Licença aberta, atualizações semestrais.',
    url: 'a r a t e k i . o r g / m a n i f e s t o',
    counter: '5 / 5',
  },

  event01: { kicker: 'E N C O N T R O   A B E R T O', day: '12', monthYear: 'J U N H O   ·   2 0 2 6', title: 'Privacidade em código aberto: um encontro técnico.', place: 'S Ã O   P A U L O  ·  S P' },
  event02: { title: 'Assembleia Arateki 2026', date: '1 2 . 0 6 . 2 6', time: '1 9 h 0 0', place: 'T E A T R O   O F I C I N A', url: 'a r a t e k i . o r g / e n c o n t r o' },
  event03: { title: 'Programação do encontro anual', date: '1 2  ·  J U N  ·  2 6', place: 'S P', schedule: [
    { time: '19:00', item: 'Abertura — Sobre autonomia' },
    { time: '19:30', item: 'Painel — Identidade soberana na prática' },
    { time: '20:45', item: 'Demonstrações técnicas (Vault, Shield)' },
    { time: '21:30', item: 'Encerramento e perguntas' },
  ]},
  event04: { kicker: 'R S V P   A B E R T O', title: 'Arateki Encontro · 2026', when: '12 de junho · 19h', where: 'Teatro Oficina  ·  SP', url: 'A R A T E K I . O R G / E N C O N T R O' },
  event05: { dateLine: '1 2 . 0 6 . 2 0 2 6', title: 'Encontro anual sobre software livre e autonomia digital.', body: 'Um dia dedicado a quem constrói, estuda ou usa tecnologias descentralizadas.', place: 'S Ã O   P A U L O', url: 'A R A T E K I . O R G / E N C O N T R O' },
  event06: { title: 'Arateki Encontro  ·  Edição 2026', date: '12  ·  Junho  ·  2026', place: 'S Ã O   P A U L O  ·  S P' },
  event07: {
    title: 'Arateki Encontro · 2026',
    date: '12 . 06 . 2026',
    gate: '0 3 A',
    city: 'S Ã O   P A U L O',
    passNum: '0 0 1',
    url: 'A R A T E K I . O R G / E N C O N T R O',
  },

  job01: { department: 'E N G E N H A R I A', role: 'Engenheiro(a) de Segurança', type: 'T e m p o   i n t e g r a l', location: 'R e m o t o   ·   L A T A M', level: 'S ê n i o r', url: 'A R A T E K I . O R G / V A G A S' },
  job02: { kicker: 'J U N T E - S E   A O   N Ú C L E O', role: 'Designer de Sistemas', summary: 'Trabalho direto sobre a linguagem visual e os componentes dos produtos Arateki. Raciocínio tipográfico, rigor geométrico, escrita técnica.', cta: 'C A N D I D A T A R', deadline: 'A T É   3 0 . 0 4' },
  job03: { role: 'Engenheiro(a) de Firmware', department: 'H A R D W A R E  ·  S H I E L D', requirements: [
    'Experiência com C embarcado em chips de segurança (Secure Element).',
    'Familiaridade com auditorias de código aberto e threat‑modeling.',
    'Escrita técnica clara em PT e EN — documentação é produto.',
    'Contribuições prévias a projetos livres (valorizado).',
  ], url: 'A R A T E K I . O R G / V A G A S' },
  job04: { kicker: 'C A R R E I R A S   A R A T E K I', role: 'Pesquisador(a) em criptografia', location: 'R E M O T O   ·   G L O B A L' },
  job05: { intro: 'Procura‑se', role: 'Engenheiro(a) de Redes P2P', model: 'H í b r i d o   ·   S P', start: 'M a i o   ·   2 0 2 6', url: 'A R A T E K I . O R G / V A G A S' },
  job06: { tagline: 'Construímos ferramentas para quem prefere autonomia a conveniência. Se isso soa familiar, venha trabalhar conosco.', url: 'A R A T E K I . O R G / V A G A S', roles: [
    { title: 'Engenheiro(a) de Segurança', team: 'E N G E N H A R I A' },
    { title: 'Designer de Sistemas', team: 'D E S I G N' },
    { title: 'Pesquisador(a) em Criptografia', team: 'P & D' },
    { title: 'Escritor(a) Técnico(a)', team: 'D O C S' },
  ] },
  job07: {
    headline: 'Por que trabalhar na Arateki.',
    sym1: '⊕', title1: 'Equipe distribuída',     desc1: 'Trabalho remoto por padrão. Encontros presenciais opcionais e custeados.',
    sym2: '◇', title2: 'Transparência radical',  desc2: 'Salários públicos por nível. Avaliações abertas. Sem opacidade interna.',
    sym3: '⏣', title3: 'Tempo de pesquisa',      desc3: 'Um dia por semana dedicado a estudo, contribuição open source ou projeto pessoal técnico.',
    sym4: '◐', title4: 'Equilíbrio real',         desc4: 'Sem cultura de heroísmo. Jornada de 35h. Férias mínimas de 30 dias.',
    url: 'A R A T E K I . O R G / V A G A S',
  },

  blog01: { category: 'E S C R I T O S  ·  T É C N I C O', title: 'Por que toda aplicação moderna precisa de um modelo de ameaça.', excerpt: 'Um convite à disciplina: antes da arquitetura, do design, do código — o threat model. Uma leitura curta sobre por que ele é o documento mais importante de qualquer projeto sério.', readTime: '7   M I N', url: 'A R A T E K I . O R G / B L O G' },
  blog02: { tags: ['C R I P T O G R A F I A', 'E N S A I O'], title: 'Contra a custódia: um ensaio sobre chaves próprias.', author: 'E Q U I P E   A R A T E K I', date: '2 3 . 0 4 . 2 6', url: 'A R A T E K I . O R G / B L O G' },
  blog03: { kicker: 'N o v o   n o   b l o g', title: 'Identidade é substantivo, não serviço.', subtitle: 'Três anos pensando em identidade digital — e o que aprendemos sobre não terceirizá‑la.', readTime: '1 1   M I N', author: 'E Q U I P E   A R A T E K I' },
  blog04: { number: '04', series: 'S É R I E  ·  F U N D A M E N T O S', title: 'O que significa software livre em 2026?', excerpt: 'Quarto artigo da série sobre os fundamentos que sustentam o projeto Arateki — software livre como infraestrutura de liberdade, não apenas licença.', url: 'A R A T E K I . O R G / B L O G' },
  blog05: { title: 'A estética do essencial: notas sobre desenho de sistemas.', author: 'E q u i p e   A r a t e k i', readTime: '9   m i n', url: 'A R A T E K I . O R G / B L O G', date: '2 3 . 0 4 . 2 6' },
  blog06: { headline: 'Novidades desta semana no blog.', articles: [
    { title: 'Contra a custódia: um ensaio sobre chaves próprias', time: '1 1   m i n' },
    { title: 'Zero‑knowledge na prática: três exemplos simples', time: '8   m i n' },
    { title: 'Por que rejeitamos telemetria por padrão', time: '6   m i n' },
    { title: 'A estética do essencial: notas de design', time: '9   m i n' },
  ], url: 'A R A T E K I . O R G / B L O G' },
  blog07: {
    section: 'E D I T O R I A L  ·  T É C N I C O',
    date: '2 5 . 0 4 . 2 6',
    title: 'O que ainda chamamos de privacidade.',
    dek: 'Notas sobre o uso e o desuso da palavra — e por que é hora de voltar à raiz.',
    byline: 'P O R   E Q U I P E   A R A T E K I',
    readTime: '1 2   M I N',
    body: 'A palavra "privacidade" passou por tantos contextos nos últimos vinte anos que já não significa o mesmo para duas pessoas em uma mesma sala. Há quem use o termo para falar de proteção contra vigilância estatal; há quem use para descrever opções num menu de configurações; há quem chame de privacidade aquilo que, tecnicamente, é apenas a ilusão dela. Voltar ao significado original — autonomia sobre dados, sobre identidade, sobre o que se compartilha e com quem — exige um exercício de precisão. Privacidade não é segredo: é o poder de escolha. Não é silêncio: é controle sobre a voz. Não é anonimato: é seletividade. Quando dizemos que um sistema respeita a privacidade do usuário, estamos dizendo, na prática, que esse sistema não retira dele o direito de decidir. Tudo o mais — criptografia, descentralização, código aberto — são meios para preservar essa decisão. A confusão entre privacidade e segredo é o que permite a serviços corporativos prometerem o primeiro enquanto operam o oposto: transparência interna sobre os dados de quem os usa, em troca de opacidade externa sobre o que fazem com eles. É uma inversão deliberada. E enquanto não a nomearmos com clareza, continuaremos negociando autonomia por conveniência.',
    url: 'A R A T E K I . O R G / B L O G',
  },

  transp01: {
    title: 'Saúde do código aberto.',
    label1: 'Código auditado externamente', val1: '92',
    label2: 'Repositórios públicos',         val2: '100',
    label3: 'Issues documentadas',           val3: '87',
    label4: 'Dependências com licença livre', val4: '74',
    tag: '2 0 2 6',
  },
  transp02: {
    heroLabel: 'P R I N C Í P I O',
    hero: 'Nenhum dado do usuário passa por servidores da Arateki.',
    cell1l: 'C Ó D I G O',      cell1v: '100% aberto',
    cell2l: 'A U D I T O R I A', cell2v: 'Externa · anual',
    cell3l: 'S E R V I D O R',   cell3v: 'Zero custódia',
    cell4l: 'L I C E N Ç A',    cell4v: 'AGPL-3.0',
  },
  transp03: {
    title: 'Marcos de construção.',
    year1: '2 0 2 4', event1: 'Fundação da Arateki. Primeiros experimentos com Hypercore e ESP32.',
    year2: '2 0 2 5', event2: 'Vault em beta. Shield em prototipagem. Auditoria de segurança contratada.',
    year3: '2 0 2 6', event3: 'Vault 1.0 lançado. Auditoria pública concluída. Raiznet em campo.',
  },
  transp04: {
    band: '1 0 0 %   C Ó D I G O   A B E R T O',
    above: 'Cada linha do Vault e do Shield é pública, auditável e licenciada sob AGPL-3.0.',
    below: 'AGPL-3.0 garante que qualquer derivação permaneça aberta. Nenhum fork proprietário é legalmente possível — esta é a proteção da comunidade, não da empresa.',
    source: 'L I C E N Ç A   ·   A G P L - 3 . 0   ·   A R A T E K I',
  },
  transp05: {
    statement: 'A Arateki nunca viu os dados dos seus usuários.',
    note1: 'A arquitetura é local-first: chaves e dados gerados no dispositivo do usuário, nunca transitam por servidores da empresa.',
    note2: 'Servidores públicos da Raiznet são peers opcionais — não têm acesso privilegiado aos dados.',
    note3: 'Auditoria de terceiros conduzida anualmente. Relatório publicado em arateki.org/auditoria.',
  },
  transp06: {
    title: 'O que a Arateki não faz.',
    label1: 'Coleta de telemetria',       value1: 'Nunca',
    label2: 'Custódia de chaves',         value2: 'Nunca',
    label3: 'Login centralizado',         value3: 'Nunca',
    label4: 'Venda de dados',             value4: 'Nunca',
    label5: 'Software proprietário',      value5: 'Nunca',
  },
  transp07: {
    title: 'Para onde vai cada hora de engenharia.',
    label1: 'Software livre · core',     val1: '52 %',
    label2: 'Auditoria e segurança',     val2: '28 %',
    label3: 'Documentação e ensino',     val3: '20 %',
    totalLabel: '100',
    tag: '2 0 2 6',
  },

  product01: {
    kicker: 'S O F T W A R E',
    name: 'Vault',
    spec1l: 'P L A T A F O R M A',  spec1v: 'Linux · macOS · Windows',
    spec2l: 'L I C E N Ç A',        spec2v: 'AGPL-3.0',
    spec3l: 'C R I P T O G R A F I A', spec3v: 'Ed25519 · AES-256-GCM',
    spec4l: 'B A C K U P',           spec4v: 'BIP-39 seed phrase',
    spec5l: 'A U T E N T I C A Ç Ã O', spec5v: 'Local · sem servidor',
    spec6l: 'D I S P O N I B I L I D A D E', spec6v: 'Gratuito · código aberto',
  },
  product02: {
    product: 'Vault',
    stat: '256',
    unit: 'bit AES',
    context: 'Chaves armazenadas com AES-256-GCM. Zero acesso de terceiros em repouso.',
    tag: 'S E G U R A N Ç A',
  },
  product03: {
    title: 'Produtos Arateki · 2026',
    date1: 'Q 1   ·   2 0 2 6',  product1: 'Vault v1.0',  note1: 'Gerenciador de chaves local. AGPL-3.0.',
    date2: 'Q 2   ·   2 0 2 6',  product2: 'Shield',       note2: 'Módulo físico de identidade soberana.',
    date3: 'Q 4   ·   2 0 2 6',  product3: 'Vault v2.0',   note3: 'Desktop Tauri + Hardware Security Module.',
  },
  product04: {
    name: 'Shield',
    version: 'H A R D W A R E   ·   V 1 . 0   ·   2 0 2 6',
    description: 'Módulo físico de identidade soberana. Alumínio anodizado, chip EAL6+, firmware auditável.',
    specs: 'USB-C  ·  NFC  ·  18 g  ·  EAL6+\nAGPL-3.0  ·  54 × 19 × 3 mm',
    tag: 'A R A T E K I   H A R D W A R E',
  },
  product05: {
    product: 'Vault',
    rel1: 'v 1.0  ·  Abril 2026',  notes1: 'Arquitetura inicial de chaves. Interface mínima. Auditoria externa concluída. Licença AGPL-3.0.',
    rel2: 'v 1.1  ·  Junho 2026',  notes2: 'Suporte a BIP-39. Exportação segura offline. Integração nativa com Shield.',
    rel3: 'v 2.0  ·  Q4 2026',     notes3: 'App desktop Tauri. Hardware Security Module. Sincronização multi-device.',
  },
  product06: {
    kicker: 'F I C H A   T É C N I C A',
    name: 'Vault Shield',
    r1l: 'M A T E R I A L',    r1v: 'Alumínio anodizado',
    r2l: 'C O N E X Ã O',      r2v: 'USB-C · NFC',
    r3l: 'C H I P',             r3v: 'Secure Element EAL6+',
    r4l: 'F I R M W A R E',    r4v: 'Código aberto · verificável',
    r5l: 'P E S O',             r5v: '18 g',
    r6l: 'D I M E N S Õ E S',  r6v: '54 × 19 × 3 mm',
  },
  product07: {
    title: 'Vault vs. gerenciadores convencionais.',
    colA: 'Vault',
    colB: 'Outros',
    attr1: 'Código aberto e auditável',                a1: '✓', b1: '—',
    attr2: 'Chaves geradas e mantidas localmente',     a2: '✓', b2: '×',
    attr3: 'Sem servidor de autenticação',             a3: '✓', b3: '×',
    attr4: 'Backup via BIP-39 offline',                a4: '✓', b4: '—',
    attr5: 'Custódia de terceiros',                    a5: '×', b5: '✓',
    tag: 'P · 0 7   ·   2 0 2 6',
  },

  testimonial01: {
    initial: 'R',
    quote: 'O Vault resolveu o que nenhuma ferramenta corporativa havia conseguido: me dar controle real sobre minhas chaves sem abrir mão da praticidade.',
    author: 'Ricardo Alves',
    role: 'Engenheiro de Segurança · Fintech SP',
  },
  testimonial02: {
    highlight: '"Controle real sem abrir mão da praticidade."',
    quote: 'O Vault resolveu o que nenhuma ferramenta corporativa havia conseguido: me dar controle sobre minhas chaves sem abrir mão da praticidade. Uso há 6 meses e não voltaria atrás.',
    author: 'Ricardo Alves',
    role: 'Engenheiro de Segurança · Fintech SP',
  },
  testimonial03: {
    author: 'Fernanda Lopes',
    role: 'Jornalista investigativa',
    company: 'A G Ê N C I A   P Ú B L I C A   ·   S P',
    quote: 'Finalmente posso conversar com fontes sem depender de aplicativos controlados por terceiros. A Arateki entende o que privacidade realmente significa.',
  },
  testimonial04: {
    date: '1 5 . 0 4 . 2 0 2 6',
    salutation: 'Para a Arateki,',
    quote: 'Quando falo em soberania de dados para produtores rurais, o Vault e a Raiznet são meus exemplos concretos. Mostro que tecnologia pode ser deles — não dos servidores de uma empresa.',
    author: 'Carlos Mendes',
    role: 'Técnico Agrícola · Goiás',
  },
  testimonial05: {
    product: 'Vault',
    feature: 'G E R E N C I A M E N T O   D E   C H A V E S',
    quote: 'Antes do Vault, eu tinha chaves SSH em três lugares e torcia para não vazar. Agora tudo está offline, auditável e é meu.',
    author: 'Ana Beatriz Costa',
    role: 'Desenvolvedora · Open Source Contributor',
  },
  testimonial06: {
    company: 'Raiznet',
    author: 'Luiz Henrique Prado',
    role: 'Fundador · Cooperativa AgroLivre',
    quote: 'Implementamos a Raiznet em 8 propriedades familiares. Pela primeira vez, os dados do plantio pertencem aos próprios produtores.',
  },
  testimonial07: {
    initial: 'M',
    author: 'Mariana Schwartz',
    role: 'Pesquisadora · Direitos digitais',
    quote: 'O que diferencia o Vault não é a interface — é o modelo. Nada do que faço passa por servidor algum. Isso muda completamente a relação de poder com a ferramenta.',
    memberId: 'AR-2024-0837',
    since: '0 8 . 2 0 2 4',
  },

  usecase01: {
    sector: 'J O R N A L I S M O',
    persona: 'Repórter investigativo',
    scenario: 'Precisa proteger fontes confidenciais. Toda comunicação com informantes passa por chaves assimétricas geridas localmente — sem servidor de e-mail, sem rastreamento.',
    tool: 'Vault',
    result: 'Identidade da fonte intacta',
    tag: '2 0 2 6',
  },
  usecase02: {
    eyebrow: 'Como uma cooperativa agrícola monitora 12 estufas sem internet.',
    challengeText: 'Área rural com conectividade instável. Telemetria de pH, temperatura e umidade chegava tarde ou nunca.',
    solutionText: 'ESP32 em cada estufa formando malha ESP-NOW local. Dados sincronizados quando há sinal; operação contínua sem ele.',
    resultText: 'Monitoramento em tempo real para 12 estufas. Alertas automáticos. Zero dependência de nuvem.',
  },
  usecase03: {
    sector: 'Ativismo',
    description: 'Grupos de direitos humanos assinam documentos sensíveis sem expor identidade. Cada assinatura é verificável — sem intermediário.',
    tool: 'V A U L T   ·   A S S I N A T U R A   D I G I T A L',
    context: 'D I R E I T O S   H U M A N O S   ·   L A T A M',
  },
  usecase04: {
    persona: 'Desenvolvedor independente',
    before: 'Chaves SSH e tokens de API espalhados em arquivos de texto. Um vazamento de repositório exporia credenciais de produção.',
    now: 'Vault gerencia todas as chaves. Assina commits localmente. Nenhuma credencial toca o repositório — mesmo por acidente.',
    tool: 'V A U L T   ·   D E S E N V O L V I M E N T O',
  },
  usecase05: {
    title: 'Monitoramento de aquaponia urbana.',
    who: 'Produtor urbano · Curitiba · PR',
    what: 'Controle de pH, temperatura e nível de água em sistema aquapônico fechado',
    how: 'Sensores ESP32 em torre PVC · malha local Raiznet · dashboard em tempo real',
    outcome: 'Perdas reduzidas em 40% · alertas antes da falha · dados soberanos',
  },
  usecase06: {
    title: 'Onde o Vault é usado hoje.',
    sector1: 'J O R N A L I S M O',
    case1: 'Proteção de fontes em investigações sensíveis via comunicação criptografada.',
    tool1: 'V A U L T',
    sector2: 'A G R I C U L T U R A',
    case2: 'Assinatura de contratos de safra sem cartório — verificável por qualquer parte.',
    tool2: 'V A U L T   +   R A I Z N E T',
    sector3: 'D E S E N V O L V I M E N T O',
    case3: 'Gestão de chaves de infraestrutura sem exposição em repositórios.',
    tool3: 'V A U L T',
  },
  usecase07: {
    title: 'Cooperativa AgroLivre · primeiro semestre de operação.',
    subtitle: 'Implantação da Raiznet em 8 propriedades familiares no centro-oeste brasileiro.',
    label1: 'P R O P R I E D A D E S',     val1: '8',     unit1: 'unidades',
    label2: 'S E N S O R E S   E M   C A M P O', val2: '32', unit2: 'devices',
    label3: 'P E R D A   D E   S A F R A',  val3: '−40',  unit3: '%',
    label4: 'D A D O S   E M   C U S T Ó D I A', val4: '0', unit4: 'servidores',
    context: 'D A D O S   ·   2 0 2 6',
    year: 'Q 2  ·  2 6',
  },

  tutorial01: {
    category: 'C O M O   F A Z E R',
    title: 'Configure o Vault em 4 passos.',
    step1: 'Baixe o instalador em arateki.org/vault',
    step2: 'Execute e confirme as permissões do sistema',
    step3: 'Gere seu par de chaves Ed25519 localmente',
    step4: 'Guarde a frase-semente offline e em local seguro',
    tag: 'V A U L T',
  },
  tutorial02: {
    title: 'Chave na nuvem vs. chave no dispositivo.',
    before: 'Chave privada no servidor do provedor. Acesso condicionado ao login. Vulnerável a vazamentos centralizados.',
    after: 'Chave gerada e mantida no seu dispositivo. Nenhum servidor intermedia o acesso. Você é o único custodiante.',
  },
  tutorial03: {
    context: 'Vault CLI',
    line1: 'vault init --keygen ed25519',
    line2: 'vault sign --key ~/.vault/id.key contrato.pdf',
    line3: 'vault verify --pub ~/.vault/id.pub contrato.pdf',
    line4: 'vault export --format bip39',
    line5: '',
    tag: 'C L I   ·   V A U L T',
  },
  tutorial04: {
    category: 'S E G U R A N Ç A   ·   V A U L T',
    label: 'D I C A',
    tip: 'Nunca fotografe sua frase-semente. Papel ou metal — sem nuvem.',
    context: 'B o a s   p r á t i c a s   ·   V a u l t',
  },
  tutorial05: {
    title: 'Antes de lançar código aberto.',
    item1: 'Licença explícita em todos os repositórios',
    item2: 'Documentação de instalação testada do zero',
    item3: 'Segredos e chaves fora do histórico git',
    item4: 'CI verificando builds nas plataformas-alvo',
    item5: 'Política de contribuição (CONTRIBUTING.md)',
    tag: 'S O F T W A R E   L I V R E',
  },
  tutorial06: {
    category: 'F L U X O   ·   A S S I N A T U R A',
    title: 'Como uma assinatura Ed25519 funciona.',
    node1: 'Você tem uma chave privada. Ela nunca sai do dispositivo.',
    node2: 'O Vault assina localmente. Gera uma assinatura de 64 bytes.',
    node3: 'Qualquer um verifica com sua chave pública — sem revelar a chave privada.',
    tag: 'C R I P T O G R A F I A',
  },
  tutorial07: {
    title: 'Sua chave precisa de hardware dedicado?',
    q1: 'você assina mais de cinco transações sensíveis por semana — ou guarda chaves de produção em ambiente compartilhado.',
    yes: 'Use o Shield. Hardware dedicado isola a chave do sistema operacional e exige confirmação física para cada operação.',
    no: 'O Vault em desktop é suficiente. Mantenha a frase-semente offline em papel ou metal e habilite a confirmação por senha.',
    tag: 'S E G U R A N Ç A',
  },

  quote01: {
    quote: 'A perfeição é atingida não quando não há mais nada a acrescentar, mas quando não há mais nada a retirar.',
    author: 'Antoine de Saint-Exupéry',
    role: 'Escritor · Piloto · 1900–1944',
    year: '2 0 2 6',
  },
  quote02: {
    date: '1 9 8 4',
    quote: 'A privacidade não é sobre esconder algo. É sobre autonomia: o poder de controlar a própria narrativa.',
    author: 'Whitfield Diffie',
    context: 'C O - C R I A D O R   ·   C R I P T O G R A F I A   D E   C H A V E   P Ú B L I C A',
  },
  quote03: {
    quote: 'Simples.\nNão simplório.',
    author: 'Dieter Rams',
    year: '1 9 7 6',
  },
  quote04: {
    eyebrow: 'V O Z   E X T E R N A   ·   D E S I G N',
    author: 'Dieter Rams',
    source: 'Dez Princípios do Bom Design  ·  1976',
    quote: 'Um bom design é o mínimo de design possível. Menos, mas melhor — porque se concentra nos aspectos essenciais e os produtos não são sobrecarregados com o supérfluo.',
  },
  quote05: {
    quoteA: 'A vigilância em massa é a antítese da liberdade.',
    authorA: 'Edward Snowden',
    roleA: 'Analista de Inteligência · Ativista',
    quoteB: 'Código aberto é a única forma real de auditoria pública.',
    authorB: 'Bruce Schneier',
    roleB: 'Criptógrafo · Pesquisador de Segurança',
  },
  quote06: {
    eyebrow: 'E N S A I O   ·   T E C N O L O G I A',
    quote: 'Há uma diferença fundamental entre ferramentas que trabalham para você e ferramentas que trabalham sobre você. O design ético começa por saber de qual lado a ferramenta está.',
    author: 'Anil Dash',
    role: 'CEO Glitch · Escritor de Tecnologia',
    detail: '2 0 2 3',
  },
  quote07: {
    eyebrow: 'A N O T A Ç Ã O   ·   M A R G I N Á L I A',
    note1: 'Escrito originalmente em correspondência privada de 1975, em resposta a uma proposta de criptografia comercial.',
    note2: 'O argumento foi retomado três décadas depois nos debates sobre vigilância em massa pós-Snowden.',
    quote: 'Quem não consegue manter um segredo entre si e um pedaço de papel jamais conseguirá mantê-lo entre si e um servidor remoto.',
    author: 'Phil Zimmermann',
    source: 'C r i a d o r   d o   P G P   ·   1 9 9 1',
    tag: '2 0 2 6',
  },

  manifesto08: {
    lines: [
      'Construímos',
      'ferramentas',
      'que servem',
      'a quem',
      'as usa.',
    ],
  },
  announce08: {
    name: 'Shield',
    tag: '2 0 2 6',
    callouts: [
      { pos: 'tl', label: 'M A T E R I A L',  spec: 'Alumínio anodizado' },
      { pos: 'tr', label: 'C H I P',          spec: 'Secure Element EAL6+' },
      { pos: 'bl', label: 'F I R M W A R E', spec: 'Código aberto' },
      { pos: 'br', label: 'C O N E X Ã O',   spec: 'USB-C · NFC' },
    ],
  },
  educational08: {
    title: 'O que torna o Vault, Vault.',
    onlyA: 'Criptografia\nforte',
    both: 'Vault',
    onlyB: 'Interface\nacessível',
  },
  event08: {
    month: 'J U N H O   ·   2 0 2 6',
    title: 'Encontro Arateki',
    location: 'S Ã O   P A U L O  ·  S P',
    day: '12',
    startWeekday: 0,
    daysInMonth: 30,
  },
  job08: {
    headline: 'Como crescemos juntos.',
    url: 'A R A T E K I . O R G / V A G A S',
    levels: [
      { title: 'Sênior', desc: 'Define direção técnica · mentora · responde por arquitetura',  width: 44 },
      { title: 'Pleno',  desc: 'Conduz projetos · decisões autônomas · revisa código',         width: 68 },
      { title: 'Júnior', desc: 'Aprende fazendo · suporte direto da equipe · pareamento diário', width: 92 },
    ],
  },
  blog08: {
    kicker: 'A R A T E K I  ·  P U B L I C A Ç Ã O   T R I M E S T R A L',
    title: 'Sumário · Edição 02',
    url: 'A R A T E K I . O R G / B L O G',
    chapters: [
      { title: 'Sobre identidade soberana',         page: '0 0 4' },
      { title: 'Por que rejeitamos a custódia',     page: '0 1 8' },
      { title: 'Anatomia de um par de chaves',      page: '0 3 6' },
      { title: 'Vault em campo · 6 meses',          page: '0 5 4' },
      { title: 'O que vem depois',                  page: '0 8 2' },
    ],
  },
  transp08: {
    title: 'Commits no repositório do Vault — últimas 4 semanas.',
    tag: '2 0 2 6',
    rowLabels: ['S e m   1', 'S e m   2', 'S e m   3', 'S e m   4'],
    matrix: [
      [0.2, 0.4, 0.6, 0.3, 0.7, 0.9, 0.8],
      [0.5, 0.6, 0.8, 0.9, 0.7, 0.4, 0.3],
      [0.7, 0.5, 0.4, 0.6, 0.5, 0.8, 0.6],
      [0.9, 0.8, 0.6, 0.5, 0.7, 0.6, 0.5],
    ],
  },
  product08: {
    product: 'Vault',
    subtitle: 'Quatro camadas — do hardware à interface.',
    layers: [
      { level: 'L4', name: 'Interface',    desc: 'CLI · Desktop Tauri · Web (futuro)' },
      { level: 'L3', name: 'Domínio',      desc: 'Lógica de chaves · assinaturas · backup' },
      { level: 'L2', name: 'Criptografia', desc: 'Ed25519 · AES-256-GCM · Argon2id' },
      { level: 'L1', name: 'Hardware',     desc: 'Secure Element opcional · Shield (NFC + USB-C)' },
    ],
  },
  testimonial08: {
    quotes: [
      { text: '"Soberania na prática."',
        author: 'A n a   B .   ·   D e v',
        pos: { top: '14%',    left: '6%'   } },
      { text: '"Finalmente sem servidores intermediários."',
        author: 'C a r l o s   M .   ·   G O',
        pos: { top: '32%',    right: '5%'  } },
      { text: '"O Vault devolve o controle a quem usa."',
        author: 'R i c a r d o   A .   ·   S P',
        pos: { top: '58%',    left: '10%'  } },
      { text: '"Privacidade não é recurso — é ponto de partida."',
        author: 'F e r n a n d a   L .   ·   P E',
        pos: { top: '76%',    right: '8%'  } },
    ],
  },
  usecase08: {
    title: 'Atividade da rede Raiznet',
    window: 'Últimas 4 horas · 25 abr 2026',
    events: [
      { time: '0 4 : 1 2', loc: 'Curitiba · PR',
        action: 'Sensor T-03 reportou pH 6.4 — alerta normal.' },
      { time: '0 3 : 4 7', loc: 'Goiânia · GO',
        action: 'Nova safra registrada na cooperativa AgroLivre.' },
      { time: '0 2 : 5 1', loc: 'Joinville · SC',
        action: 'Bloco assinado por chave Ed25519 do produtor.' },
      { time: '0 2 : 0 4', loc: 'Recife · PE',
        action: 'Telemetria de 12 sensores sincronizada via Hyperswarm.' },
      { time: '0 1 : 3 8', loc: 'São Paulo · SP',
        action: 'Onboarding de novo nó no gateway público.' },
    ],
  },
  tutorial08: {
    title: 'Anatomia da pasta do Vault.',
    tree: [
      { prefix: '',         name: '~/.vault/',     annot: 'raiz do Vault' },
      { prefix: '├──',      name: 'id.key',        annot: 'chave privada · 0600' },
      { prefix: '├──',      name: 'id.pub',        annot: 'chave pública · 0644' },
      { prefix: '├──',      name: 'config.toml',   annot: 'preferências locais' },
      { prefix: '└──',      name: 'backup/',       annot: 'cópia offline' },
      { prefix: '    ├──',  name: 'seed.bip39',    annot: 'frase-semente · ler offline' },
      { prefix: '    └──',  name: 'shield.fw',     annot: 'firmware do Shield' },
    ],
  },
  quote08: {
    quote: 'Privacidade é\nautonomia,\nnão segredo.',
    author: 'P H I L   Z I M M E R M A N N',
    curved: '· A R A T E K I · 2 0 2 6 · S E L O · M A N I F E S T O · A R A T E K I · 2 0 2 6 ·',
  },
};

export { IG_DEFAULTS };
